In [1]:
#https://towardsdatascience.com/the-lstm-reference-card-6163ca98ae87
import numpy as np
import pandas as pd
from tensorflow.keras.models import load_model

In [2]:
filename = "model MSGARCH-LSTM-window5 4 neuron.h5"

In [3]:
model = load_model(filename)

In [4]:
model.summary()

Model: "sequential_163"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
lstm_163 (LSTM)              (None, 4)                 112       
_________________________________________________________________
dense_163 (Dense)            (None, 1)                 5         
Total params: 117
Trainable params: 117
Non-trainable params: 0
_________________________________________________________________


In [6]:
Wx = model.layers[1].get_weights()[0] 
bx = model.layers[1].get_weights()[1]

In [9]:
print('Wx')
print(Wx)
print(" ")
print('bx')
print(bx)

Wx
[[ 3.8670878]
 [-6.8730426]
 [-2.1128838]
 [-3.3151677]]
 
bx
[-0.3707265]


In [11]:
units = 4 #lstm units
W = model.layers[0].get_weights()[0] 
U = model.layers[0].get_weights()[1] 
b = model.layers[0].get_weights()[2]

In [12]:
W

array([[ 6.9323545e+00,  1.5781726e+00, -1.1393532e+00,  5.4640961e+00,
         5.9332666e+00, -6.2695036e+00, -2.7060137e+00,  5.2060180e+00,
        -6.2787193e-01,  1.8323486e+01,  6.2905774e+00,  4.7902322e+00,
         1.1632485e+01,  2.1577711e+00, -1.4630514e-01,  9.2864523e+00],
       [ 3.2969122e-03, -3.4293423e+00, -4.0886483e-01, -3.5516300e+00,
         1.3420497e+00, -2.7039578e+00, -2.2639103e+00, -7.4192195e+00,
        -1.5209252e+00, -1.5024332e+01, -2.6430252e+00, -2.3368886e+00,
         2.5700489e-01, -1.9157106e+00,  9.5886564e-01, -4.4378943e+00]],
      dtype=float32)

In [16]:
W_i = W[:, :units] 
W_i

array([[ 6.9323545e+00,  1.5781726e+00, -1.1393532e+00,  5.4640961e+00],
       [ 3.2969122e-03, -3.4293423e+00, -4.0886483e-01, -3.5516300e+00]],
      dtype=float32)

In [18]:
b_i = b[:units] 
b_i

array([2.423188  , 1.3003806 , 0.08820487, 1.5445478 ], dtype=float32)